---
- name: install and start ntp
  hosts: node-web

  tasks:
  - name: install ntp
    yum: name=ntp state=latest

  - name: copy ntp.conf
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    notify: restart ntpd    

  - name: start ntp service
    service: name=ntpd state=started enabled=yes

  handlers:
  - name: restart ntpd
    service: name=ntpd state=restarted
